# Generated by Django 4.1.2 on 2024-05-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laude_CustomApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sched',
            name='setID',
        ),
    ]
