# Generated by Django 4.1.2 on 2024-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laude_CustomApp', '0002_remove_sched_setid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sched',
            name='id',
        ),
        migrations.AddField(
            model_name='sched',
            name='destination',
            field=models.CharField(default='Marinduque', max_length=20),
        ),
        migrations.AddField(
            model_name='sched',
            name='origin',
            field=models.CharField(default='Lucena', max_length=20),
        ),
        migrations.AddField(
            model_name='sched',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sched',
            name='scheduleId',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sched',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sched',
            name='shipId',
            field=models.CharField(default='001', max_length=20),
        ),
        migrations.AddField(
            model_name='sched',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='sched',
            name='vehicles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sched',
            name='vessel',
            field=models.CharField(default='starhorse', max_length=20),
        ),
        migrations.AlterField(
            model_name='sched',
            name='date',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='sched',
            name='time',
            field=models.CharField(default='12:00', max_length=10),
        ),
    ]
