# Generated by Django 4.1.2 on 2024-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laude_CustomApp', '0003_remove_sched_id_sched_destination_sched_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched',
            name='scheduleId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
